[package]
name = "sd-pdf"
version = "0.1.0"
authors = ["Vítor Vasconcellos <vitor@spacedrive.com>"]
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
image = "0.24.6"
lazy_static = "1.4.0"
pdfium-render = { version ="0.8.8", features = ["sync", "image", "thread_safe"] }
thiserror = "1.0.40"
tokio = { workspace = true, features = ["fs", "io-util"] }
tracing = "0.1.37"
